# Generated by Django 5.0.2 on 2024-11-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproof', models.IntegerField()),
                ('name', models.CharField(max_length=199)),
                ('dogname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, max_length=300, null=True)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('idproof', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Muncipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muncipality_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('muncipality_email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=20)),
                ('idproof', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dog_image/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('muncipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addpet', to='shop.muncipality')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muncipality_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trainer_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(default='no address provide', max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate/')),
                ('phno', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('muncipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_reg', to='shop.muncipality')),
            ],
        ),
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('phno', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('idproof', models.IntegerField()),
                ('last_login', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muncipality_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('batchnumber', models.CharField(max_length=100)),
                ('due', models.CharField(max_length=100)),
                ('veterinarian', models.ImageField(blank=True, null=True, upload_to='veterinarian')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine', to='shop.pet')),
            ],
        ),
        migrations.DeleteModel(
            name='admin_reg',
        ),
        migrations.AddField(
            model_name='adopt',
            name='muncipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopt', to='shop.muncipality'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='shop.trainer_reg'),
        ),
    ]
