# Generated by Django 5.0.2 on 2024-11-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_adopt_age_remove_adopt_breed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopt',
            name='muncipality',
        ),
        migrations.AddField(
            model_name='adopt',
            name='muncipality_name',
            field=models.CharField(default=1, max_length=199),
            preserve_default=False,
        ),
    ]
