# Generated by Django 5.0.2 on 2024-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_adopt_muncipality_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopt',
            name='pet',
        ),
        migrations.AddField(
            model_name='adopt',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopt',
            name='breed',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopt',
            name='dogname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
