# Generated by Django 5.0.2 on 2024-11-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_pet_gender_alter_pet_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_feddback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dog_image/')),
                ('feedback_text', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
    ]
