# Generated by Django 5.1.3 on 2024-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='muncipality',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
