# Generated by Django 4.2.11 on 2024-11-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_muncipality_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinations',
            name='vaccinename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccinations',
            name='veterinarian',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
